### ISSUE TITLE
Dont see any rate limiter

### ISSUE THREAD

**Issue by jpalala** [maxmechanic/node-pinboard#6]
It might be a good idea to somehow restrict the requests for the posts/all and posts/recent calls 
As per pinboard api terms https://pinboard.in/api/#ratellimits :

> Rate Limits
> 
> API requests are limited to one call per user every three seconds, except for the following:
> 
> posts/all - once every five minutes
> posts/recent - once every minute
> If you need to make unusually heavy use of the API, please consider discussing it with me first, to avoid unhappiness.
> 
> Make sure your API clients check for 429 Too Many Requests server errors and back off appropriately. If possible, keep doubling the interval between requests until you stop receiving errors.

**Comment by maxmechanic** [comment]
I'm not sure that throttling requests should be the responsibility of this library. Using something like [Lodash's throttle](https://lodash.com/docs#throttle), this issue can be handled as needed, without resulting in an extra library-level dependency for those that are unlikely to encounter the rate limit:

``` javascript
const throttle = require('lodash.throttle')
const Pinboard = require('node-pinboard')

const pinboard = new Pinboard(process.env.PINBOARD_TOKEN)
const throttledRecent = throttle(pinboard.recent.bind(pinboard), 3000)

setInterval(() => throttledRecent(console.log), 100)

```

How would see that being implemented in a way that is transparent to the lib user? I think the main advantage would be getting errors or warnings when you are requesting too aggressively, but I'm on the fence as far as who should be accountable for that.

**Comment by maxmechanic** [comment]
Leaving this to user-land for now, but open to discussion still.
